/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthCallbackRouteImport } from './routes/auth-callback'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CreatorRouteImport } from './routes/creator'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreatorIndexRouteImport } from './routes/creator.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SuperadminSettingsRouteImport } from './routes/superadmin.settings'
import { Route as SuperadminDashboardRouteImport } from './routes/superadmin.dashboard'
import { Route as CreatorStatusRouteImport } from './routes/creator.status'
import { Route as CreatorSettingsRouteImport } from './routes/creator.settings'
import { Route as CreatorNotificationsRouteImport } from './routes/creator.notifications'
import { Route as CreatorNewRouteImport } from './routes/creator.new'
import { Route as CreatorMetricsRouteImport } from './routes/creator.metrics'
import { Route as CreatorCalendarRouteImport } from './routes/creator.calendar'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminContentsRouteImport } from './routes/admin.contents'
import { Route as AdminCalendarRouteImport } from './routes/admin.calendar'
import { Route as AdminBrandsRouteImport } from './routes/admin.brands'
import { Route as AdminApprovalRouteImport } from './routes/admin.approval'
import { Route as AdminExportRouteImport } from './routes/admin.export'

const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth-callback',
  path: '/auth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorRoute = CreatorRouteImport.update({
  id: '/creator',
  path: '/creator',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorIndexRoute = CreatorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CreatorRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SuperadminSettingsRoute = SuperadminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminDashboardRoute = SuperadminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => SuperadminRoute,
} as any)
const CreatorStatusRoute = CreatorStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorSettingsRoute = CreatorSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorNotificationsRoute = CreatorNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorNewRoute = CreatorNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorMetricsRoute = CreatorMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorCalendarRoute = CreatorCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => CreatorRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentsRoute = AdminContentsRouteImport.update({
  id: '/contents',
  path: '/contents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBrandsRoute = AdminBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApprovalRoute = AdminApprovalRouteImport.update({
  id: '/approval',
  path: '/approval',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExportRoute = AdminExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/creator': typeof CreatorRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/pending': typeof PendingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/admin/approval': typeof AdminApprovalRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/contents': typeof AdminContentsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/creator/calendar': typeof CreatorCalendarRoute
  '/creator/metrics': typeof CreatorMetricsRoute
  '/creator/new': typeof CreatorNewRoute
  '/creator/notifications': typeof CreatorNotificationsRoute
  '/creator/settings': typeof CreatorSettingsRoute
  '/creator/status': typeof CreatorStatusRoute
  '/superadmin/dashboard': typeof SuperadminDashboardRoute
  '/superadmin/settings': typeof SuperadminSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/creator/': typeof CreatorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/pending': typeof PendingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/admin/approval': typeof AdminApprovalRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/contents': typeof AdminContentsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/creator/calendar': typeof CreatorCalendarRoute
  '/creator/metrics': typeof CreatorMetricsRoute
  '/creator/new': typeof CreatorNewRoute
  '/creator/notifications': typeof CreatorNotificationsRoute
  '/creator/settings': typeof CreatorSettingsRoute
  '/creator/status': typeof CreatorStatusRoute
  '/superadmin/dashboard': typeof SuperadminDashboardRoute
  '/superadmin/settings': typeof SuperadminSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/creator': typeof CreatorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/creator': typeof CreatorRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/pending': typeof PendingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/admin/approval': typeof AdminApprovalRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/contents': typeof AdminContentsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/creator/calendar': typeof CreatorCalendarRoute
  '/creator/metrics': typeof CreatorMetricsRoute
  '/creator/new': typeof CreatorNewRoute
  '/creator/notifications': typeof CreatorNotificationsRoute
  '/creator/settings': typeof CreatorSettingsRoute
  '/creator/status': typeof CreatorStatusRoute
  '/superadmin/dashboard': typeof SuperadminDashboardRoute
  '/superadmin/settings': typeof SuperadminSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/creator/': typeof CreatorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/auth-callback'
    | '/creator'
    | '/forgot-password'
    | '/pending'
    | '/reset-password'
    | '/superadmin'
    | '/verify-email'
    | '/admin/approval'
    | '/admin/brands'
    | '/admin/calendar'
    | '/admin/contents'
    | '/admin/dashboard'
    | '/admin/export'
    | '/admin/notifications'
    | '/admin/settings'
    | '/creator/calendar'
    | '/creator/metrics'
    | '/creator/new'
    | '/creator/notifications'
    | '/creator/settings'
    | '/creator/status'
    | '/superadmin/dashboard'
    | '/superadmin/settings'
    | '/admin/'
    | '/creator/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth-callback'
    | '/forgot-password'
    | '/pending'
    | '/reset-password'
    | '/superadmin'
    | '/verify-email'
    | '/admin/approval'
    | '/admin/brands'
    | '/admin/calendar'
    | '/admin/contents'
    | '/admin/dashboard'
    | '/admin/export'
    | '/admin/notifications'
    | '/admin/settings'
    | '/creator/calendar'
    | '/creator/metrics'
    | '/creator/new'
    | '/creator/notifications'
    | '/creator/settings'
    | '/creator/status'
    | '/superadmin/dashboard'
    | '/superadmin/settings'
    | '/admin'
    | '/creator'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/auth-callback'
    | '/creator'
    | '/forgot-password'
    | '/pending'
    | '/reset-password'
    | '/superadmin'
    | '/verify-email'
    | '/admin/approval'
    | '/admin/brands'
    | '/admin/calendar'
    | '/admin/contents'
    | '/admin/dashboard'
    | '/admin/export'
    | '/admin/notifications'
    | '/admin/settings'
    | '/creator/calendar'
    | '/creator/metrics'
    | '/creator/new'
    | '/creator/notifications'
    | '/creator/settings'
    | '/creator/status'
    | '/superadmin/dashboard'
    | '/superadmin/settings'
    | '/admin/'
    | '/creator/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CreatorRoute: typeof CreatorRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  PendingRoute: typeof PendingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SuperadminRoute: typeof SuperadminRouteWithChildren
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator': {
      id: '/creator'
      path: '/creator'
      fullPath: '/creator'
      preLoaderRoute: typeof CreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/': {
      id: '/creator/'
      path: '/'
      fullPath: '/creator/'
      preLoaderRoute: typeof CreatorIndexRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/superadmin/settings': {
      id: '/superadmin/settings'
      path: '/settings'
      fullPath: '/superadmin/settings'
      preLoaderRoute: typeof SuperadminSettingsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/dashboard': {
      id: '/superadmin/dashboard'
      path: '/dashboard'
      fullPath: '/superadmin/dashboard'
      preLoaderRoute: typeof SuperadminDashboardRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/creator/status': {
      id: '/creator/status'
      path: '/status'
      fullPath: '/creator/status'
      preLoaderRoute: typeof CreatorStatusRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/settings': {
      id: '/creator/settings'
      path: '/settings'
      fullPath: '/creator/settings'
      preLoaderRoute: typeof CreatorSettingsRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/notifications': {
      id: '/creator/notifications'
      path: '/notifications'
      fullPath: '/creator/notifications'
      preLoaderRoute: typeof CreatorNotificationsRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/new': {
      id: '/creator/new'
      path: '/new'
      fullPath: '/creator/new'
      preLoaderRoute: typeof CreatorNewRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/metrics': {
      id: '/creator/metrics'
      path: '/metrics'
      fullPath: '/creator/metrics'
      preLoaderRoute: typeof CreatorMetricsRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/calendar': {
      id: '/creator/calendar'
      path: '/calendar'
      fullPath: '/creator/calendar'
      preLoaderRoute: typeof CreatorCalendarRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contents': {
      id: '/admin/contents'
      path: '/contents'
      fullPath: '/admin/contents'
      preLoaderRoute: typeof AdminContentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/brands': {
      id: '/admin/brands'
      path: '/brands'
      fullPath: '/admin/brands'
      preLoaderRoute: typeof AdminBrandsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/approval': {
      id: '/admin/approval'
      path: '/approval'
      fullPath: '/admin/approval'
      preLoaderRoute: typeof AdminApprovalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/export': {
      id: '/admin/export'
      path: '/export'
      fullPath: '/admin/export'
      preLoaderRoute: typeof AdminExportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth-callback': {
      id: '/auth-callback'
      path: '/auth-callback'
      fullPath: '/auth-callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminApprovalRoute: typeof AdminApprovalRoute
  AdminBrandsRoute: typeof AdminBrandsRoute
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminContentsRoute: typeof AdminContentsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminExportRoute: typeof AdminExportRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApprovalRoute: AdminApprovalRoute,
  AdminBrandsRoute: AdminBrandsRoute,
  AdminCalendarRoute: AdminCalendarRoute,
  AdminContentsRoute: AdminContentsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminExportRoute: AdminExportRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CreatorRouteChildren {
  CreatorCalendarRoute: typeof CreatorCalendarRoute
  CreatorMetricsRoute: typeof CreatorMetricsRoute
  CreatorNewRoute: typeof CreatorNewRoute
  CreatorNotificationsRoute: typeof CreatorNotificationsRoute
  CreatorSettingsRoute: typeof CreatorSettingsRoute
  CreatorStatusRoute: typeof CreatorStatusRoute
  CreatorIndexRoute: typeof CreatorIndexRoute
}

const CreatorRouteChildren: CreatorRouteChildren = {
  CreatorCalendarRoute: CreatorCalendarRoute,
  CreatorMetricsRoute: CreatorMetricsRoute,
  CreatorNewRoute: CreatorNewRoute,
  CreatorNotificationsRoute: CreatorNotificationsRoute,
  CreatorSettingsRoute: CreatorSettingsRoute,
  CreatorStatusRoute: CreatorStatusRoute,
  CreatorIndexRoute: CreatorIndexRoute,
}

const CreatorRouteWithChildren =
  CreatorRoute._addFileChildren(CreatorRouteChildren)

interface SuperadminRouteChildren {
  SuperadminDashboardRoute: typeof SuperadminDashboardRoute
  SuperadminSettingsRoute: typeof SuperadminSettingsRoute
}

const SuperadminRouteChildren: SuperadminRouteChildren = {
  SuperadminDashboardRoute: SuperadminDashboardRoute,
  SuperadminSettingsRoute: SuperadminSettingsRoute,
}

const SuperadminRouteWithChildren = SuperadminRoute._addFileChildren(
  SuperadminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CreatorRoute: CreatorRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  PendingRoute: PendingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SuperadminRoute: SuperadminRouteWithChildren,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
